# Generated by Django 5.0.6 on 2024-06-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=60)),
                ('direccionResidencia', models.CharField(max_length=60)),
                ('correo', models.CharField(max_length=150)),
                ('tipoUsuario', models.IntegerField(choices=[(1, 'Lector'), (2, 'Bibliotecario'), (3, 'Administrador')])),
            ],
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(max_length=60),
        ),
    ]
