# Generated by Django 3.2.14 on 2024-08-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='num_disponible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='num_ocupados',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_multa', models.DateField()),
                ('valor_multa', models.ImageField(upload_to='')),
                ('estado_multa', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Pagado')])),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multa', to='libreria.prestamo')),
                ('usuario_multado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multa', to='libreria.usuario')),
            ],
        ),
    ]
