# Generated by Django 3.2.14 on 2024-08-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_auto_20240806_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='valor_multa',
            field=models.IntegerField(),
        ),
    ]
